#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use KindlingCLI\Command\InitCommand;
use KindlingCLI\Command\InstallCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new InstallCommand);
$application->add(new InitCommand);

$application->run();
