#!/usr/bin/env php
<?php
if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use Symfony\Component\Console\Application;

define('PRESS_BIN', __dir__ .'/bin');
define('PRESS_WP', PRESS_BIN . '/wp');

$application = new Application();

$application->add(new \PressCLI\Command\WPCLIInstallCommand);
$application->add(new \PressCLI\Command\WPCLIUpdateCommand);

$application->run();
