#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use KindlingCLI\Command\NewCommand;
use KindlingCLI\Command\InstallCommand;
use KindlingCLI\Command\ConfigureCommand;
use Symfony\Component\Console\Application;

define('KCLI_EXEC_DIR', __DIR__);

putenv('WP_CLI_CONFIG_PATH='.KCLI_EXEC_DIR . '/config.yml');

$application = new Application();

$application->add(new InstallCommand);
$application->add(new ConfigureCommand);
$application->add(new NewCommand);

$application->run();
